name: Docker Image CI

on:
  push:
    branches: [ "gateway", "user", "auth" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout 
      uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}   
    -
      name: Build image
      run: docker build . -t ${{secrets.DOCKER_USERNAME}}/cesi-learning-${{github.ref_name}}:latest
    -
      name: Push to docker hub
      run: docker image push ${{secrets.DOCKER_USERNAME}}/cesi-learning-${{github.ref_name}}:latest
