name: Docker Image CI

on:
  push:
    branches: [ "gateway", "user", "auth" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout 
      uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}   
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/cesi-learning-${{ github.ref_name }}:latest
